In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets, ensemble
from sklearn.metrics import mean_squared_error

In [8]:
data=pd.read_csv('datacleaned.csv')
data=data.drop(['Unnamed: 0'], axis=1)

In [14]:
for x in range(1,39):
    print("GW",x,len(data[data['GW']==x]))

GW 1 106
GW 2 106
GW 3 106
GW 4 106
GW 5 106
GW 6 106
GW 7 106
GW 8 106
GW 9 106
GW 10 106
GW 11 106
GW 12 106
GW 13 106
GW 14 106
GW 15 106
GW 16 106
GW 17 106
GW 18 106
GW 19 106
GW 20 106
GW 21 106
GW 22 106
GW 23 106
GW 24 106
GW 25 106
GW 26 106
GW 27 106
GW 28 106
GW 29 106
GW 30 106
GW 31 106
GW 32 106
GW 33 106
GW 34 106
GW 35 106
GW 36 106
GW 37 106
GW 38 106

# Only taking data from gameweeks 5+

In [15]:
data=data[data['GW']>5]

In [16]:
data

,team,playerid,name,assists,clean_sheets,creativity,goals_conceded,goals_scored,ict_index,influence,...,saves,team_a_score,team_h_score,threat,total_points,value,was_home,yellow_cards,GW,fdr
530,1,11,Pierre-Emerick_Aubameyang_11,0,0,1.6,2,1,9.5,34.6,...,0,2.0,3.0,59.0,5,110,True,1,6,2.0
531,1,12,Alexandre_Lacazette_12,0,0,0.0,0,0,0.0,0.0,...,0,2.0,3.0,0.0,0,94,True,0,6,2.0
532,1,14,Bernd_Leno_14,0,0,0.0,2,0,3.7,37.4,...,7,2.0,3.0,0.0,2,50,True,1,6,2.0
533,2,29,Jack_Grealish_29,1,0,46.3,3,0,9.0,37.4,...,0,2.0,3.0,6.0,6,59,False,0,6,3.0
534,3,42,Lewis_Dunk_42,0,1,0.6,0,0,5.8,21.0,...,0,0.0,0.0,36.0,6,46,False,1,6,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023,1,488,Nicolas_Pépé_488,0,0,17.6,1,1,7.3,36.2,...,0,1.0,2.0,19.0,8,93,False,0,30,2.0
4024,3,494,Aaron_Ramsdale_494,0,0,0.0,2,0,0.2,2.2,...,0,2.0,0.0,0.0,1,45,True,0,30,2.0
4025,4,502,Neal_Maupay_502,0,0,1.8,1,1,10.6,38.6,...,0,1.0,2.0,66.0,9,57,True,0,30,3.0
4026,18,525,Ismaïla_Sarr_525,0,0,6.8,1,0,3.6,8.2,...,0,1.0,1.0,21.0,2,64,True,0,30,3.0
4027,12,618,Bruno Miguel_Borges Fernandes_618,0,0,26.6,1,1,12.4,52.4,...,0,1.0,1.0,45.0,9,86,False,0,30,4.0